### ISSUE TITLE
[Help] Some objects are ignored

### ISSUE THREAD

**Issue by tonysxn** [atombottle/cs2-map-parser#2]
Hi
Thanks for your release
I found out that some objects like doors, boxes, cars are ignored
Look like hulls are okay
But for some reason it doesnt calculate it on intersect
Can you help with this?

![image](https://github.com/atombottle/cs2-map-parser/assets/170427228/59e1d0e3-0ce3-4cbd-aa72-51cccfeb278a)
![image](https://github.com/atombottle/cs2-map-parser/assets/170427228/e2efdbaa-f212-465f-9014-fdd8cfe99ad3)
![image](https://github.com/atombottle/cs2-map-parser/assets/170427228/5cd5755d-5d3d-4b30-992c-e88f07e39857)
![image](https://github.com/atombottle/cs2-map-parser/assets/170427228/bb195e4c-28d2-4d88-bd8c-92b6a5f3c8e8)

**Comment by atombottle** [comment]
have you tried other collision index?

**Comment by tonysxn** [comment]
Thanks
For another people with this problem
On dd you need to remove "if (collision_index) == 0"
To get all meshes

**Comment by atombottle** [comment]
> Thanks For another people with this problem On dd you need to remove "if (collision_index) == 0" To get all meshes

This is because of use playerclip, hulls are missing , but currently I have no idea about it
