### ISSUE TITLE
Issue regarding decompiling the new CS2 maps

### ISSUE THREAD

**Issue by JannesBonk** [atombottle/cs2-map-parser#3]
I've succesfully decompiled the non-community maps, but the new maps such as ar_pool_day or de_mills do not have the ".vphys_c" file.
![image](https://github.com/atombottle/cs2-map-parser/assets/86556266/2d3a0438-57a5-4b76-9d1f-7550dbff882f)
I've seen some people say that using the ".vmdl_c" provided by the map is the correct way to go.
Some analysis later, it turns out they are pretty similar.

![image](https://github.com/atombottle/cs2-map-parser/assets/86556266/cf6991f3-41a1-4ef0-9b2e-b1e8b1aaa799)
![image](https://github.com/atombottle/cs2-map-parser/assets/86556266/e2e7062d-1066-4a01-8e3d-d5709b9c87f0)

**Comment by atombottle** [comment]
I've checked mills, the world_physics file contains data parser need. I think it also works for other community maps.

**Comment by JannesBonk** [comment]
> I've checked mills, the world_physics file contains data parser need. I think it also works for other community maps.

indeed it does!
